### ISSUE TITLE
Unable to connect to Ergodox-EZ

### ISSUE THREAD

**Issue by jlanzarotta** [kiibohd/configurator#86]
Just downloaded your software... it looks really good.  However, it is unable to connect to my Ergodox-EZ.  I am running Windows 7.  Any ideas?

Thanks,

**Comment by timvisee** [comment]
I don't think this software supports the `Ergodox EZ`. This software is ment to be used with an `Ergodox Infinity` instead.

Even though they are both Ergodox keyboards, they are quite a bit different under the hood (which is why I don't think the EZ would work).

You should take a look at the online EZ configurator instead; [here](https://configure.ergodox-ez.com).

**Comment by jbondeson** [comment]
@timvisee is right on the money: same layout, complete different internals.
